### ISSUE TITLE
[Feature]: Add kerberos and TLS support for HDFS

### ISSUE THREAD

**Issue by lwpk110** [zncdatadev/hdfs-operator#56]
### Have you searched existing issues?  🔎

I have searched and found no existing issues

### Summary 💡

This issue is focused on enhancing our HDFS setup by adding support for Kerberos authentication and TLS. We will leverage the secret-operator to generate the necessary Kerberos and TLS secrets, and ensure that end-to-end (E2E) tests are updated to cover these new features.

#### Summary
This issue is focused on enhancing our HDFS setup by adding support for Kerberos authentication and TLS. We will leverage the secret-operator to generate the necessary Kerberos and TLS secrets, and ensure that end-to-end (E2E) tests are updated to cover these new features.

#### Example
**Add Kerberos Authentication Support**:
    - Integrate Kerberos authentication into the HDFS setup.
    - Use the secret-operator to generate Kerberos CSI secrets.

```yaml
# Example configuration for Kerberos and TLS integration
spec:
  image:
    repository: quay.io/zncdatadev/hadoop
    tag: 3.3.4
  clusterConfig:
    zookeeperDiscoveryZNode: sample-hdfs-znode
    authentication:
      tls:
        secretClass: tls
        jksPassword: "123456"
      kerberos:
        secretClass: kerberos-hdfs
```

### Motivation 🔦

Adding Kerberos and TLS support to our HDFS setup is crucial for enhancing security and meeting compliance requirements. Kerberos provides strong authentication, while TLS ensures secure communication. By leveraging the secret-operator for secret management, we streamline the process and maintain consistency across our deployments. Updating the E2E tests ensures that these new features are thoroughly tested and integrated smoothly into our system.
